### ISSUE TITLE
User story 1: responsive design and easy to access navigation

### ISSUE THREAD

**Issue by TezzStrom** [TezzStrom/pm1-gamers-corner#6]
**User story**

I want easy navigation, a responsive design across devices and a user-friendly interface to avoid frustration when trying to find information. 

**Acceptance criteria**

- [ ] The website is fully responsive across all devices.
- [ ] The navigation is intuitive and easy to access.

**Tasks**

- [ ] Apply responsive design using Bootstrap.
- [ ] Arrange the website's layout and navigation based on best practices.
